# Generated by Django 3.2.3 on 2021-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherBoys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
