# Generated by Django 3.2.3 on 2021-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherBoys_app', '0002_alter_store_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
